init:
  - git config --global core.autocrlf true
build_script:
  - ps: .\dotnetbuild.ps1
clone_depth: 1
version: 0.0.{build}
nuget:
  project_feed: true
artifacts:
  - path: '**\*.nupkg'
services:
  - mongodb 

