init:
  - git config --global core.autocrlf true
build_script:
  - ps: .\build.ps1 $env:APPVEYOR_BUILD_VERSION
clone_depth: 1
version: 0.0.{build}
nuget:
  project_feed: true
artifacts:
  - path: Releases\$env:APPVEYOR_BUILD_VERSION\Release\*.nupkg
 

